<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jstl</string>
		<string>jsp</string>
		<string>tag</string>
	</array>
	<key>name</key>
	<string>JSTL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;)([a-zA-Z0-9:]++)(?=[^&gt;]*&gt;&lt;/\2&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;)(&lt;)(/)(\2)(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html meta.scope.between-tag-pair.html</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.any.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#jstl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;\?)(xml)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.xml.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\?&gt;)</string>
			<key>name</key>
			<string>meta.tag.preprocessor.xml.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-generic-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;!--</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>--\s*&gt;</string>
			<key>name</key>
			<string>comment.block.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>--</string>
					<key>name</key>
					<string>invalid.illegal.bad-comments-or-CDATA.html</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;!</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&gt;</string>
			<key>name</key>
			<string>meta.tag.sgml.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i:DOCTYPE)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.doctype.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=&gt;)</string>
					<key>name</key>
					<string>meta.tag.sgml.doctype.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>"[^"&gt;]*"</string>
							<key>name</key>
							<string>string.quoted.double.doctype.identifiers-and-DTDs.html</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[CDATA\[</string>
					<key>end</key>
					<string>]](?=&gt;)</string>
					<key>name</key>
					<string>constant.other.inline-data.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\s*)(?!--|&gt;)\S(\s*)</string>
					<key>name</key>
					<string>invalid.illegal.bad-comments-or-CDATA.html</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#embedded-code</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?:^\s+)?(&lt;)((?i:style))\b(?![^&gt;]*/&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.style.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=&lt;/(?:[sS][tT][yY][lL][eE]))(&gt;)(?:\s*\n)?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.style.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!&lt;/(?:[sS][tT][yY][lL][eE]))(&gt;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.style.html</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.css.embedded.html</string>
					<key>end</key>
					<string>(&lt;/)((?i:style))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>/\*</string>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.css</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\*/|(?=&lt;/[sS][tT][yY][lL][eE])</string>
							<key>name</key>
							<string>comment.block.css</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.css</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?:^\s+)?(&lt;)((?i:script))\b(?![^&gt;]*/&gt;)(?!.*type=["']text/(?:template|html)['"])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.script.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=&lt;/([sS][cC][rR][iI][pP][tT]))(&gt;)(?:\s*\n)?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.script.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!&lt;/(?:[sS][cC][rR][iI][pP][tT]))(&gt;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.script.html</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.js.embedded.html</string>
					<key>end</key>
					<string>(&lt;/)((?i:script))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.js</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(//).*?((?=&lt;/[sS][cC][rR][iI][pP][tT])|$\n?)</string>
							<key>name</key>
							<string>comment.line.double-slash.js</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>/\*</string>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.js</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\*/|(?=&lt;/[sS][cC][rR][iI][pP][tT])</string>
							<key>name</key>
							<string>comment.block.js</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#jstl</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#jstl-variable</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;/?)((?i:body|head|html)\b)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.structure.any.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.structure.any.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;/?)((?i:address|blockquote|dd|div|dl|dt|fieldset|form|frame|frameset|h1|h2|h3|h4|h5|h6|iframe|noframes|object|ol|p|ul|applet|center|dir|hr|menu|pre)\b)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.block.any.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.block.any.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;/?)((?i:a|abbr|acronym|area|b|base|basefont|bdo|big|br|button|caption|cite|code|col|colgroup|del|dfn|em|font|head|html|i|img|input|ins|isindex|kbd|label|legend|li|link|map|meta|noscript|optgroup|option|param|q|s|samp|script|select|small|span|strike|strong|style|sub|sup|table|tbody|td|textarea|tfoot|th|thead|title|tr|tt|u|var)\b)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.inline.any.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>((?: ?/)?&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.inline.any.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;/?)([a-zA-Z0-9:]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.other.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.other.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#entities</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;&gt;</string>
			<key>name</key>
			<string>invalid.illegal.incomplete.html</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;</string>
			<key>name</key>
			<string>invalid.illegal.bad-angle-bracket.html</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>embedded-code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#php</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#python</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded-jstl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#jstl-variable</string>
				</dict>
			</array>
		</dict>
		<key>embedded-jstl</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>jstl (all) tags</string>
					<key>match</key>
					<string>(&lt;)(\/)([a-zA-Z0-9^\ ]*?)(:.*?)(&gt;)</string>
					<key>name</key>
					<string>keyword.control.jstl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;)([a-zA-Z0-9]*?)(:.*?)</string>
					<key>comment</key>
					<string>jstl tags</string>
					<key>end</key>
					<string>\/&gt;|&gt;</string>
					<key>name</key>
					<string>keyword.control.jstl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>jstl tags attributes</string>
							<key>match</key>
							<string>([a-zA-Z0-9-]*)(?=(=("|')))</string>
							<key>name</key>
							<string>constant.other.directive.attribute.jstl</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>jstl costant inside tags</string>
							<key>match</key>
							<string>=</string>
							<key>name</key>
							<string>keyword.operator.assignment.jstl</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(")</string>
							<key>comment</key>
							<string>jstl text inside double quoted attributs</string>
							<key>end</key>
							<string>(")</string>
							<key>name</key>
							<string>string.quoted.double.jstl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#jstl-variable</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(')</string>
							<key>comment</key>
							<string>jstl text inside double quoted attributs</string>
							<key>end</key>
							<string>(')</string>
							<key>name</key>
							<string>string.quoted.single.jstl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#jstl-variable</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>entities</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.entity.html</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&amp;)([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
					<key>name</key>
					<string>constant.character.entity.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;</string>
					<key>name</key>
					<string>invalid.illegal.bad-ampersand.html</string>
				</dict>
			</array>
		</dict>
		<key>jstl</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>jstl (all) tags</string>
					<key>match</key>
					<string>(&lt;)(\/)([a-zA-Z0-9^\ ]*?)(:.*?)(&gt;)</string>
					<key>name</key>
					<string>punctuation.section.directive.jstl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;)([a-zA-Z0-9]*?)(:.*?)</string>
					<key>comment</key>
					<string>jstl tags</string>
					<key>end</key>
					<string>\/&gt;|&gt;</string>
					<key>name</key>
					<string>punctuation.section.directive.jstl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>jstl tags attributes</string>
							<key>match</key>
							<string>([a-zA-Z0-9-]*)(?=(=("|')))</string>
							<key>name</key>
							<string>constant.other.directive.attribute.jstl</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>jstl costant inside tags</string>
							<key>match</key>
							<string>=</string>
							<key>name</key>
							<string>keyword.operator.assignment.jstl</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(")</string>
							<key>comment</key>
							<string>jstl text inside double quoted attributs</string>
							<key>end</key>
							<string>(")</string>
							<key>name</key>
							<string>string.quoted.double.jstl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#jstl-variable</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(')</string>
							<key>comment</key>
							<string>jstl text inside double quoted attributs</string>
							<key>end</key>
							<string>(')</string>
							<key>name</key>
							<string>string.quoted.single.jstl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#jstl-variable</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;%--</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.jsp</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>jsp comments</string>
					<key>end</key>
					<string>--%&gt;</string>
					<key>name</key>
					<string>comment.block.jsp</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;%@</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.directive.jsp</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>jsp tags</string>
					<key>end</key>
					<string>%&gt;</string>
					<key>name</key>
					<string>meta.directive.jsp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\w+</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>keyword.other.directive.jsp</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=%&gt;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\w+</string>
									<key>name</key>
									<string>constant.other.directive.attribute.jsp</string>
								</dict>
								<dict>
									<key>match</key>
									<string>=</string>
									<key>name</key>
									<string>keyword.operator.assignment.jsp</string>
								</dict>
								<dict>
									<key>begin</key>
									<string>"</string>
									<key>beginCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.jsp</string>
										</dict>
									</dict>
									<key>end</key>
									<string>"</string>
									<key>endCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.jsp</string>
										</dict>
									</dict>
									<key>name</key>
									<string>string.quoted.double.jsp</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>\\.</string>
											<key>name</key>
											<string>constant.character.escape.jsp</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>begin</key>
									<string>'</string>
									<key>beginCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.begin.jsp</string>
										</dict>
									</dict>
									<key>end</key>
									<string>'</string>
									<key>endCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.string.end.jsp</string>
										</dict>
									</dict>
									<key>name</key>
									<string>string.quoted.single.jsp</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>match</key>
											<string>\\.</string>
											<key>name</key>
											<string>constant.character.escape.jsp</string>
										</dict>
									</array>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;%[!=]?)|(&lt;jsp:scriptlet&gt;|&lt;jsp:expression&gt;|&lt;jsp:declaration&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.jsp</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.tag.block.jsp</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>script tag</string>
					<key>end</key>
					<string>(?&lt;=&lt;/jsp:scriptlet&gt;|&lt;/jsp:expression&gt;|&lt;/jsp:declaration&gt;|%&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>meta.tag.block.jsp</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.embedded.jsp</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(&lt;/jsp:scriptlet&gt;|&lt;/jsp:expression&gt;|&lt;/jsp:declaration&gt;)|(%&gt;)</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\n)(?!&lt;/jsp:scriptlet&gt;|&lt;/jsp:expression&gt;|&lt;/jsp:declaration&gt;|%&gt;|\{|\})</string>
							<key>end</key>
							<string>(?=&lt;/jsp:scriptlet&gt;|&lt;/jsp:expression&gt;|&lt;/jsp:declaration&gt;|%&gt;|\{|\})|\n</string>
							<key>name</key>
							<string>source.java.embedded.jsp</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.java</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>{</string>
							<key>end</key>
							<string>}</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>(&lt;/jsp:scriptlet&gt;|&lt;/jsp:expression&gt;|&lt;/jsp:declaration&gt;)|(%&gt;)</string>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>meta.tag.block.jsp</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.section.embedded.jsp</string>
										</dict>
									</dict>
									<key>end</key>
									<string>(&lt;jsp:scriptlet&gt;|&lt;jsp:expression&gt;|&lt;jsp:declaration&gt;)|(&lt;%[!=]?)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>text.html.jsp</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>include</key>
									<string>source.java</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>source.java</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>jstl-variable</key>
		<dict>
			<key>begin</key>
			<string>\${</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>variable.parameter.jstl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>elements inside variables</string>
					<key>match</key>
					<string>( (and |or )(empty|not empty|\!empty) )|( (and|or|not empty|empty|\!empty|lt|gt|le|ge|eq|ne|\?|:|&amp;&amp;|==|&gt;=|&lt;=|&gt;|&lt;|\!=|\!|\+|\\|\/|-|%) )|(\?|:|&amp;&amp;|==|&gt;=|&lt;=|&gt;|&lt;|\!=|\!|\+|\\|\/|-|%|\)|\()</string>
					<key>name</key>
					<string>keyword.jstl</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>elements inside variables</string>
					<key>match</key>
					<string>([a-zA-Z0-9]*?)(:)(.*?)(?=\()</string>
					<key>name</key>
					<string>keyword.jstl</string>
				</dict>
			</array>
		</dict>
		<key>php</key>
		<dict>
			<key>begin</key>
			<string>(?=(^\s*)?&lt;\?)</string>
			<key>end</key>
			<string>(?!(^\s*)?&lt;\?)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.php</string>
				</dict>
			</array>
		</dict>
		<key>python</key>
		<dict>
			<key>begin</key>
			<string>(?:^\s*)&lt;\?python(?!.*\?&gt;)</string>
			<key>contentName</key>
			<string>source.python.embedded.html</string>
			<key>end</key>
			<string>\?&gt;(?:\s*$\n)?</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<key>ruby</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;%+#</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.erb</string>
						</dict>
					</dict>
					<key>end</key>
					<string>%&gt;</string>
					<key>name</key>
					<string>comment.block.erb</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;%+(?!&gt;)=?</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.ruby</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.ruby.embedded.html</string>
					<key>end</key>
					<string>-?%&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.ruby</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(#).*?(?=-?%&gt;)</string>
							<key>name</key>
							<string>comment.line.number-sign.ruby</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.ruby</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;\?r(?!&gt;)=?</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.ruby.nitro</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.ruby.nitro.embedded.html</string>
					<key>end</key>
					<string>-?\?&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.ruby.nitro</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(#).*?(?=-?\?&gt;)</string>
							<key>name</key>
							<string>comment.line.number-sign.ruby.nitro</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.ruby</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>tag-generic-attribute</key>
		<dict>
			<key>match</key>
			<string>\b([a-zA-Z\-:]+)</string>
			<key>name</key>
			<string>entity.other.attribute-name.html</string>
		</dict>
		<key>tag-id-attribute</key>
		<dict>
			<key>begin</key>
			<string>\b(id)\b\s*(=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.id.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;='|")</string>
			<key>name</key>
			<string>meta.attribute-with-value.id.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.html</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.toc-list.id.html</string>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#embedded-code</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#entities</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.html</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.toc-list.id.html</string>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#embedded-code</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#entities</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>tag-stuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-id-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-generic-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.jstl</string>
	<key>uuid</key>
	<string>17994EC8-6B1D-11D9-AC3A-000D93589AF6</string>
</dict>
</plist>
